### ISSUE TITLE
UBC 还是 UCB ？

### ISSUE THREAD

**Issue by JaydenYL** [scwong-seminar/scwong-seminar.github.io#1]
https://scwong-seminar.github.io/moments/wang-tong.html 中， 第二段第二句，UBC是英属哥伦比亚大学，在加拿大，UCB才是美国的加州伯克利，想问一下这个地方是不是typo？

**Comment by zerotal** [comment]
是ubc，wong在加拿大待过很久，没有在加州待过。这句与美国矛盾，但原文如此

**Comment by JaydenYL** [comment]
明白了，谢谢你的解释！
